### ISSUE TITLE
The system cannot find the path specified

### ISSUE THREAD

**Issue by BoquanErwinChen** [jan-rybizki/Chempy#14]
I am trying to run the tutorial notebooks, but I encounter an error every time an input file is required. Here is the error message when I am trying to run the first tutorial. 

`---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-5-b4a9a48c007b> in <module>
      1 # First we load the default solar abundances from Asplund 2009
      2 
----> 3 basic_solar = solar_abundances()
      4 getattr(basic_solar, a.solar_abundance_name)()

C:\ProgramData\Anaconda3\lib\site-packages\Chempy\solar_abundance.py in __init__(self)
     12                 Upon initialization the element names and numbers and masses are loaded and the solar table loaded. The values are filled after using one of the methods which will load solar abundance literature values into the table.
     13 		'''
---> 14                 self.table = np.load(localpath + 'input/elemental_table.npy')
     15                 ## Python3 need transformation between bytes and strings
     16                 element_list = []

C:\ProgramData\Anaconda3\lib\site-packages\numpy\lib\npyio.py in load(file, mmap_mode, allow_pickle, fix_imports, encoding)
    413         own_fid = False
    414     else:
--> 415         fid = open(os_fspath(file), "rb")
    416         own_fid = True
    417 

FileNotFoundError: [Errno 2] No such file or directory: '/input/elemental_table.npy'`

**Comment by jan-rybizki** [comment]
Sorry, I have accidentally turned off the notifications.
I believe that with the latest commit today a 'localpath' was added and the tutorials should run.
